import {StyleSheet} from 'react-native';
import React from 'react';
const styles = StyleSheet.create({
  headerContainerStylePortrait: {
    flex: 0.4,
    backgroundColor: 'red',
    width: '100%',
  },
  descriptionContainerStylePortrait: {
    flex: 0.7,
    backgroundColor: 'white',
    width: '150%',
    transform: [{rotateZ: '5deg'}],
    marginLeft: -20,
    marginTop: -15,
    marginBottom: -40,
  },
  headerContainerStyleLandscap: {
    flex: 0.4,
    backgroundColor: 'red',
    width: '100%',
  },
  descriptionContainerStyleLandscap: {
    flex: 0.7,
    backgroundColor: 'white',
    width: '150%',
    transform: [{rotateZ: '5deg'}],
    marginLeft: -20,
    marginTop: -15,
    marginBottom: -40,
  },
  headBGImgStylePortrait: {
    flex: 1,
    width: '100%',
  },
  headerProfileContainerPortrait: {
    marginTop: 50,
    marginLeft: 20,
    flexDirection: 'row',
  },
  headerProfileContainerLandscap: {
    marginTop: 0,
    marginLeft: '10%',
    flexDirection: 'row',
  },
  headerProfileImgPortrait: {
    height: 70,
    width: 70,
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 35,
  },
  headerProfileImgLandscap: {
    height: 50,
    width: 50,
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 25,
  },
  headerProfileTextContainerPortrait: {
    alignItems: 'center',
    height: 70,
    justifyContent: 'center',
    marginLeft: 20,
  },
  headerProfileTextContainerLandscape: {
    alignItems: 'center',
    height: 50,
    justifyContent: 'center',
    marginLeft: 20,
  },
  alignBtnCenterPortrait: {
    backgroundColor: '#e01667',
    height: 150,
    width: 150,
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 75,
    position: 'absolute',
    top: '25.5%',
    left: '70%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alignBtnCenterLandscap: {
    backgroundColor: '#e01667',
    height: 50,
    width: 50,
    borderColor: 'red',
    borderWidth: 1,
    borderRadius: 25,
    position: 'absolute',
    top: '35%',
    left: '85%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verticalLineDescription: {
    backgroundColor: 'gray',
    height: '100%',
    width: 1,
    marginLeft: 30,
    transform: [{rotateZ: '-5deg'}],
  },
  titleStylePortrait: {
    fontSize: 20,
  },
  titleStyleLandscape: {
    fontSize: 15,
  },
  subTitleStylePortrait: {
    fontSize: 10,
    color: 'gray',
  },
  subTitleStyleLandscape: {
    fontSize: 7,
    color: 'gray',
  },
  greenDotStylePortrait: {
    backgroundColor: 'green',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '25%',
    left: '3.3%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
    // transform: [{rotateZ: '-5deg'}],
  },
  greenDotStyleLandscape: {
    backgroundColor: 'green',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '35%',
    left: '2.5%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  taskDescription_GreenDotContainerPortrait: {
    // backgroundColor: 'red',
    height: 50,
    width: '50%',
    position: 'absolute',
    top: '15%',
    left: '10%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    transform: [{rotateZ: '-5deg'}],
  },
  taskDescription_GreenDotContainerLandscape: {
    // backgroundColor: 'red',
    height: 35,
    width: '80%',
    position: 'absolute',
    top: '13%',
    left: '10%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    transform: [{rotateZ: '-6deg'}],
  },
  pinkDotStylePortrait: {
    backgroundColor: 'pink',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '40%',
    left: '4.3%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
    // transform: [{rotateZ: '-5deg'}],
  },
  pinkDotStyleLandscape: {
    backgroundColor: 'pink',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '57%',
    left: '3%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  taskDescription_PinkDotContainerPortrait: {
    // backgroundColor: 'red',
    height: 50,
    width: '50%',
    position: 'absolute',
    top: '30%',
    left: '12%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    transform: [{rotateZ: '-5.3deg'}],
  },
  taskDescription_PinkDotContainerLandscape: {
    // backgroundColor: 'red',
    height: 35,
    width: '80%',
    position: 'absolute',
    top: '32%',
    left: '11%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    transform: [{rotateZ: '-7deg'}],
  },
  yellowDotStylePortrait: {
    backgroundColor: '#8DB600',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '57%',
    left: '5.8%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  yellowDotStyleLandscape: {
    backgroundColor: '#8DB600',
    height: 10,
    width: 10,
    position: 'absolute',
    top: '75%',
    left: '3.4%',
    borderColor: 'transparent',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  taskDescription_yellowDotContainerPortrait: {
    // backgroundColor: 'red',
    height: 50,
    width: '50%',
    position: 'absolute',
    top: '45%',
    left: '14%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    transform: [{rotateZ: '-6deg'}],
  },
  taskDescription_yellowDotContainerLandscape: {
    // backgroundColor: 'red',
    height: 35,
    width: '80%',
    position: 'absolute',
    top: '55%',
    left: '15%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tickBtnContainerStyle: {
    position: 'absolute',
    top: 10,
  },
  clockBtnContainerStyle: {
    position: 'absolute',
    top: '25%',
    left: 15,
  },
  exclamationBtnContainerStyle: {
    position: 'absolute',
    top: '60%',
    left: 20,
  },
  bottomTickBtnContainerStyle: {
    position: 'absolute',
    top: '75%',
    left: 60,
  },
  cancelBtnStyle: {
    position: 'absolute',
    borderColor: 'transparent',
    borderWidth: 0.5,
    height: 40,
    width: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
    opacity: 0.2,
  },
  contributorImgContainer: {
    height: 50,
    width: '80%',
    position: 'absolute',
    top: '60%',
    left: '15%',
    flexDirection: 'row',
    // justifyContent: 'space-between',
    alignItems: 'center',
    transform:[{rotateZ: '-5deg'}]
  },
});

export default styles;
